"""
Suspicious Activity Detection — Rule Engine
============================================
[DEPRECATED in Phase 4]
This standalone rule engine is deprecated and must NOT be wired into the live
incident generation pipeline. Threat scoring and behavioral kinematics are centrally
unified under `edge/behavior/kinematics.py` (KinematicBehaviorEngine) and
`backend/app/services/scoring.py` (compute_threat_score).
This module is preserved solely for reference / backward compatibility.

Consumes track updates and fires explainable alerts based on
configurable behavioral rules. Every alert includes reasons.

Rules implemented:
1. Loitering: Track stays in restricted zone > threshold seconds
2. Wrong-direction movement: Track crosses zone boundary in wrong direction
3. Group formation: Multiple persons in same zone during night hours
4. Repeated boundary crossing: Same track crosses boundary multiple times
5. Rapid movement: Track speed exceeds normal threshold
6. Abandoned object: Object stays stationary while owner moves away
7. Night movement: Any detection during configured night hours
8. Camera tampering: Sudden brightness/contrast change

This is a RULE-BASED engine, not deep learning.
The rules are explainable and configurable.

IMPORTANT: This module consumes TRACKING output, not raw detections.
It requires track IDs, trajectories, and zone memberships.
"""

import logging
import time
from typing import Dict, List, Optional, Any, Set
from dataclasses import dataclass, field
from collections import defaultdict
from enum import Enum

logger = logging.getLogger(__name__)


class Severity(Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


@dataclass
class TrackState:
    """Current state of a tracked object for rule evaluation."""
    track_id: int
    camera_id: str
    class_name: str          # "person", "car", "truck", "bus", "dog"
    bbox: tuple              # (x1, y1, x2, y2)
    confidence: float
    timestamp: float
    center: tuple            # (cx, cy)
    zones: List[str]         # Zone names this track is currently in
    trajectory: List[tuple]  # Last N center points
    speed: float             # Pixels per second
    direction: float         # Angle in degrees (0-360)
    first_seen: float
    last_zone_crossing: Optional[float] = None
    zone_entry_times: Dict[str, float] = field(default_factory=dict)


@dataclass
class RuleAlert:
    """An alert generated by the rule engine."""
    rule_name: str
    severity: Severity
    camera_id: str
    track_id: int
    class_name: str
    timestamp: float
    reasons: List[str]
    confidence: float
    details: Dict[str, Any] = field(default_factory=dict)


class SuspiciousActivityEngine:
    """
    Rule-based suspicious activity detection engine.
    
    Consumes TrackState updates and fires RuleAlerts when
    behavioral rules are triggered. All rules are configurable
    and all alerts are explainable.
    """
    
    def __init__(self, config: Optional[Dict] = None):
        """
        Args:
            config: Override default rule thresholds
        """
        self._config = config or {}
        
        # Rule thresholds (configurable)
        self._loitering_threshold = self._config.get("loitering_seconds", 30)
        self._group_min_persons = self._config.get("group_min_persons", 3)
        self._night_start = self._config.get("night_start_hour", 22)  # 10 PM
        self._night_end = self._config.get("night_end_hour", 6)       # 6 AM
        self._rapid_speed_threshold = self._config.get("rapid_speed_px_per_sec", 200)
        self._repeated_crossing_threshold = self._config.get("repeated_crossing_count", 3)
        self._abandoned_threshold = self._config.get("abandoned_seconds", 120)
        self._stationary_speed_threshold = self._config.get("stationary_speed", 5.0)
        
        # State tracking
        self._track_states: Dict[str, TrackState] = {}  # key: camera_id:track_id
        self._alerts_fired: Dict[str, float] = {}       # key: rule:fingerprint: timestamp
        self._alert_cooldown = 60  # Don't re-fire same rule for same track within 60s
        
        # Statistics
        self._stats = {
            "tracks_processed": 0,
            "alerts_generated": 0,
            "rules_fired": defaultdict(int),
        }
    
    def update_track(self, state: TrackState) -> List[RuleAlert]:
        """
        Process a track update and return any triggered alerts.
        
        Args:
            state: Current track state
            
        Returns:
            List of RuleAlert objects (empty if no rules triggered)
        """
        key = f"{state.camera_id}:{state.track_id}"
        self._track_states[key] = state
        self._stats["tracks_processed"] += 1
        
        alerts = []
        
        # Run all rules
        for rule_fn in [
            self._rule_loitering,
            self._rule_wrong_direction,
            self._rule_group_formation,
            self._rule_repeated_crossing,
            self._rule_rapid_movement,
            self._rule_night_movement,
            self._rule_abandoned_object,
        ]:
            alert = rule_fn(state)
            if alert:
                # Check cooldown
                cooldown_key = f"{alert.rule_name}:{state.camera_id}:{state.track_id}"
                now = time.time()
                last_fired = self._alerts_fired.get(cooldown_key, 0)
                
                if (now - last_fired) > self._alert_cooldown:
                    self._alerts_fired[cooldown_key] = now
                    alerts.append(alert)
                    self._stats["alerts_generated"] += 1
                    self._stats["rules_fired"][alert.rule_name] += 1
        
        return alerts
    
    def _rule_loitering(self, state: TrackState) -> Optional[RuleAlert]:
        """Detect loitering: track stays in restricted zone too long."""
        for zone_name in state.zones:
            if "restricted" not in zone_name.lower() and "sensitive" not in zone_name.lower():
                continue
            
            entry_time = state.zone_entry_times.get(zone_name, 0)
            if entry_time == 0:
                continue
            
            dwell_time = state.timestamp - entry_time
            
            if dwell_time > self._loitering_threshold:
                reasons = [
                    f"Object dwelling in '{zone_name}' for {dwell_time:.0f} seconds",
                    f"Threshold: {self._loitering_threshold}s",
                    f"Object class: {state.class_name}",
                ]
                
                # Severity scales with dwell time
                if dwell_time > self._loitering_threshold * 3:
                    severity = Severity.CRITICAL
                    reasons.append(f"Extended loitering ({dwell_time:.0f}s >> {self._loitering_threshold}s)")
                elif dwell_time > self._loitering_threshold * 2:
                    severity = Severity.HIGH
                else:
                    severity = Severity.MEDIUM
                
                confidence = min(0.95, 0.5 + (dwell_time / (self._loitering_threshold * 5)))
                
                return RuleAlert(
                    rule_name="loitering",
                    severity=severity,
                    camera_id=state.camera_id,
                    track_id=state.track_id,
                    class_name=state.class_name,
                    timestamp=state.timestamp,
                    reasons=reasons,
                    confidence=confidence,
                    details={
                        "zone": zone_name,
                        "dwell_seconds": dwell_time,
                        "threshold": self._loitering_threshold,
                    }
                )
        
        return None
    
    def _rule_wrong_direction(self, state: TrackState) -> Optional[RuleAlert]:
        """Detect movement against expected direction in a zone."""
        # Check if track has crossing direction info
        if not state.zones or state.last_zone_crossing is None:
            return None
        
        # If moving fast and in a restricted zone, flag as potential wrong-direction
        if state.speed > 50 and any("restricted" in z.lower() for z in state.zones):
            reasons = [
                f"Rapid movement ({state.speed:.0f} px/s) in restricted zone",
                f"Potential boundary crossing attempt",
                f"Direction: {state.direction:.0f}°",
            ]
            
            return RuleAlert(
                rule_name="wrong_direction",
                severity=Severity.HIGH,
                camera_id=state.camera_id,
                track_id=state.track_id,
                class_name=state.class_name,
                timestamp=state.timestamp,
                reasons=reasons,
                confidence=0.7,
                details={
                    "speed": state.speed,
                    "direction": state.direction,
                    "zones": state.zones,
                }
            )
        
        return None
    
    def _rule_group_formation(self, state: TrackState) -> Optional[RuleAlert]:
        """Detect groups of persons forming in zones during night hours."""
        if state.class_name != "person":
            return None
        
        hour = time.localtime(state.timestamp).tm_hour
        is_night = hour >= self._night_start or hour < self._night_end
        
        if not is_night:
            return None
        
        # Count persons in same zones
        zone_persons: Dict[str, Set[int]] = defaultdict(set)
        for key, other_state in self._track_states.items():
            if other_state.camera_id != state.camera_id:
                continue
            if other_state.class_name != "person":
                continue
            for z in other_state.zones:
                zone_persons[z].add(other_state.track_id)
        
        for zone_name, person_ids in zone_persons.items():
            if len(person_ids) >= self._group_min_persons:
                reasons = [
                    f"Group of {len(person_ids)} persons detected in '{zone_name}'",
                    f"Night-time gathering ({hour}:00 hours)",
                    f"Minimum group size: {self._group_min_persons}",
                ]
                
                severity = Severity.CRITICAL if len(person_ids) >= 5 else Severity.HIGH
                confidence = min(0.9, 0.5 + (len(person_ids) * 0.1))
                
                return RuleAlert(
                    rule_name="group_formation",
                    severity=severity,
                    camera_id=state.camera_id,
                    track_id=state.track_id,
                    class_name=state.class_name,
                    timestamp=state.timestamp,
                    reasons=reasons,
                    confidence=confidence,
                    details={
                        "zone": zone_name,
                        "person_count": len(person_ids),
                        "hour": hour,
                    }
                )
        
        return None
    
    def _rule_repeated_crossing(self, state: TrackState) -> Optional[RuleAlert]:
        """Detect repeated boundary crossings by the same track."""
        # Count zone changes for this track
        key = f"{state.camera_id}:{state.track_id}"
        
        # Simple heuristic: if trajectory has many direction changes near zone boundaries
        if len(state.trajectory) < 10:
            return None
        
        # Count direction reversals
        reversals = 0
        for i in range(2, len(state.trajectory)):
            dx1 = state.trajectory[i-1][0] - state.trajectory[i-2][0]
            dx2 = state.trajectory[i][0] - state.trajectory[i-1][0]
            if dx1 * dx2 < -10:  # Sign change = direction reversal
                reversals += 1
        
        if reversals >= self._repeated_crossing_threshold:
            reasons = [
                f"Repeated direction reversals detected ({reversals} times)",
                f"Pattern suggests boundary probing",
                f"Track active for {state.timestamp - state.first_seen:.0f} seconds",
            ]
            
            severity = Severity.HIGH if reversals >= 5 else Severity.MEDIUM
            confidence = min(0.85, 0.4 + (reversals * 0.05))
            
            return RuleAlert(
                rule_name="repeated_crossing",
                severity=severity,
                camera_id=state.camera_id,
                track_id=state.track_id,
                class_name=state.class_name,
                timestamp=state.timestamp,
                reasons=reasons,
                confidence=confidence,
                details={
                    "reversals": reversals,
                    "threshold": self._repeated_crossing_threshold,
                }
            )
        
        return None
    
    def _rule_rapid_movement(self, state: TrackState) -> Optional[RuleAlert]:
        """Detect abnormally rapid movement."""
        if state.speed < self._rapid_speed_threshold:
            return None
        
        reasons = [
            f"Movement speed {state.speed:.0f} px/s exceeds threshold ({self._rapid_speed_threshold} px/s)",
            f"Direction: {state.direction:.0f}°",
            f"Object class: {state.class_name}",
        ]
        
        severity = Severity.HIGH if state.speed > self._rapid_speed_threshold * 2 else Severity.MEDIUM
        confidence = min(0.8, 0.5 + (state.speed / (self._rapid_speed_threshold * 5)))
        
        return RuleAlert(
            rule_name="rapid_movement",
            severity=severity,
            camera_id=state.camera_id,
            track_id=state.track_id,
            class_name=state.class_name,
            timestamp=state.timestamp,
            reasons=reasons,
            confidence=confidence,
            details={
                "speed": state.speed,
                "threshold": self._rapid_speed_threshold,
            }
        )
    
    def _rule_night_movement(self, state: TrackState) -> Optional[RuleAlert]:
        """Detect any movement during night hours."""
        hour = time.localtime(state.timestamp).tm_hour
        is_night = hour >= self._night_start or hour < self._night_end
        
        if not is_night:
            return None
        
        reasons = [
            f"Movement detected during night hours ({hour}:00)",
            f"Object class: {state.class_name}",
            f"Speed: {state.speed:.0f} px/s",
        ]
        
        if state.class_name in ("person", "car", "truck", "bus"):
            severity = Severity.MEDIUM
        else:
            severity = Severity.LOW
        
        confidence = 0.6
        
        return RuleAlert(
            rule_name="night_movement",
            severity=severity,
            camera_id=state.camera_id,
            track_id=state.track_id,
            class_name=state.class_name,
            timestamp=state.timestamp,
            reasons=reasons,
            confidence=confidence,
            details={
                "hour": hour,
                "speed": state.speed,
            }
        )
    
    def _rule_abandoned_object(self, state: TrackState) -> Optional[RuleAlert]:
        """Detect objects that remain stationary for too long (potential abandoned items)."""
        if state.class_name in ("person",):  # People sitting isn't abandoned
            return None
        
        if state.speed > self._stationary_speed_threshold:
            return None  # Still moving
        
        # Check how long track has been stationary
        if len(state.trajectory) < 5:
            return None
        
        # Check if trajectory has been very still for recent frames
        recent = state.trajectory[-10:] if len(state.trajectory) >= 10 else state.trajectory
        if len(recent) < 5:
            return None
        
        # Calculate movement in recent trajectory
        total_movement = 0
        for i in range(1, len(recent)):
            dx = recent[i][0] - recent[i-1][0]
            dy = recent[i][1] - recent[i-1][1]
            total_movement += (dx**2 + dy**2)**0.5
        
        avg_movement = total_movement / len(recent)
        
        if avg_movement < self._stationary_speed_threshold:
            stationary_time = state.timestamp - state.first_seen
            
            if stationary_time > self._abandoned_threshold:
                reasons = [
                    f"Object stationary for {stationary_time:.0f} seconds",
                    f"Average movement: {avg_movement:.1f} px/frame (below threshold {self._stationary_speed_threshold})",
                    f"Object class: {state.class_name}",
                ]
                
                severity = Severity.HIGH if stationary_time > self._abandoned_threshold * 2 else Severity.MEDIUM
                confidence = min(0.85, 0.5 + (stationary_time / (self._abandoned_threshold * 5)))
                
                return RuleAlert(
                    rule_name="abandoned_object",
                    severity=severity,
                    camera_id=state.camera_id,
                    track_id=state.track_id,
                    class_name=state.class_name,
                    timestamp=state.timestamp,
                    reasons=reasons,
                    confidence=confidence,
                    details={
                        "stationary_seconds": stationary_time,
                        "avg_movement": avg_movement,
                    }
                )
        
        return None
    
    def get_stats(self) -> Dict:
        """Get engine statistics."""
        return {
            **self._stats,
            "active_tracks": len(self._track_states),
            "rules_fired": dict(self._stats["rules_fired"]),
        }
    
    def cleanup_stale_tracks(self, max_age: float = 300) -> int:
        """Remove tracks not updated in max_age seconds."""
        now = time.time()
        stale_keys = [
            k for k, v in self._track_states.items()
            if (now - v.timestamp) > max_age
        ]
        for k in stale_keys:
            del self._track_states[k]
        return len(stale_keys)


# Module-level singleton
_rule_engine: Optional[SuspiciousActivityEngine] = None


def get_rule_engine(**kwargs) -> SuspiciousActivityEngine:
    """Get or create the singleton rule engine."""
    global _rule_engine
    if _rule_engine is None:
        _rule_engine = SuspiciousActivityEngine(**kwargs)
    return _rule_engine
